@startuml
title アクティビティ図（タスク編集画面)
:開始;

if(タスクを編集して保存したら)then(yes)
    :変更内容をサーバへリクエスト;
    :サーバからデータベースへ変更を保存;
    if(正常に保存出来たら)then(yes)
        :サーバから保存したことをレスポンス;
    else(no)
        :保存できなかったことをレスポンス;
    endif
    :メイン画面に変更内容を反映させる;
elseif(タスクを削除したら)then(yes)
    :変更内容をサーバへリクエスト;
    :サーバからデータベースに該当データの削除を実行;
    if(削除に成功したら)then(yes)
        :サーバから削除したことをレスポンス;
    else(no)
        :エラーが発生したことをレスポンス;
    endif
else(no)
endif
:終了;
@enduml