@startuml
title アクティビティ図（メイン画面）
:開始;
if(期限の近いタスクがあったら) then(yes)
    :アラームメッセージを出す;
elseif(タスク（シャボン）をクリックしたら) then(yes)
    :サーバにタスク情報を参照要求;
    :サーバからデータベースへアクセス
    :データベースからサーバへデータを抽出（メモ、期限、現在の状況など）;
    :サーバからメイン画面に情報をレスポンス;
    if(タスク編集ボタンをクリックしたら) then(yes)
        :タスク詳細画面へ;
        detach
    else(no)
    endif
else(no)
endif
:終了;
@enduml