@startuml
title アクティビティ図（ログイン画面）
:開始;
if(アカウント新規作成を押した) then(yes)
    :サーバに情報を送る;
    :サーバからデータベースへ送る;
    :データベースからサーバへ新規作成用のHTMLを返す;
    :サーバからHTMLのデータを受け取る;
    :新規作成HTML画面で情報を登録;
    :登録内容をサーバに送る;
    :サーバからデータベースへ登録する;
else(no)
endif

:"送信ボタンを押した";
:サーバに情報を送る;
:サーバからデータベースへ送る;
if("ログイン情報が正しいなら")then(yes)
    :データベースからtrueを得る;
else(no)
    :データベースからfalseを得る;
    detach
endif

:メイン画面へ遷移;

@enduml