@startuml
title アクティビティ図（カレンダー画面）

:開始;
if(日付をクリックしたら) then(yes)
    :日付情報をサーバへ送信;
    :サーバからデータベースへアクセスし、該当する日付のタスクを参照する;
    :取得したタスク情報をレスポンス;
    :メイン画面をその日の状態にする(シャボンの状態やタスクの位置など);
    :今日のタスク一覧を表示する;
else(no)

endif
:終了;
@enduml