@startuml
title シーケンス図
ログイン画面 -> サーバ : ログイン情報送信リクエスト
サーバ->データベース:ログイン情報を参照or新規登録
サーバ<-データベース:認証結果HTMLを取得
ログイン画面 <- サーバ : 認証結果か、新規作成用のHTMLをレスポンス
ログイン画面 -> メイン画面:ページ遷移
タスク登録画面 -> サーバ :タスク情報を渡すリクエスト
サーバ -> データベース: タスク登録
メイン画面 -> サーバ :タスク参照をリクエスト
サーバ -> データベース: タスクを参照
サーバ <- データベース: タスクを取得
サーバ -> タスク詳細画面:画面表示
タスク詳細画面 -> サーバ: 編集を保存
サーバ -> データベース: データを保存
サーバ -> メイン画面 :タスクを更新したHTMLをレスポンス
カレンダー画面 -> サーバ: 日付をクリック
サーバ -> データベース: 日付情報からその日のすべてのタスク情報を参照
データベース -> サーバ: その日のすべてのタスク情報を取得
サーバ -> メイン画面: カレンダーの内容を基にクリティカルパスや水の描写を反映
@enduml
